
<ul  class="navbar-nav align-middle">
                <li class="nav-item registrar-btn">
                    <a href="<?=URL?>Home/Login" class="nav-link">
                        <i class="fa-solid fa-user"></i> Ingresar / Registrarse
                    </a>
                </li>
                <li class="nav-item">
                    <a  href="" class="nav-link position-relative">
                        <i class="fa-solid fa-cart-shopping"></i>
                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-morado">
                            99+
                            <span class="visually-hidden">unread messages</span>
                        </span>
                    </a>
                </li>
            </ul>